Refactor /bin/wttr

diff --git a/bin/wttr b/bin/wttr
--- a/bin/wttr
+++ b/bin/wttr
@@ -1,75 +1,85 @@
 #!/bin/sh
-# Get the current weather from wttr.in, with some caching
+# Get the current weather from wttr.in, with some caching.
 
-# cache location
-CACHE_FILE=${WTTR_CACHE:-"${HOME}/.cache/wttr/cached"}
-# cache ttl in seconds
-CACHE_TTL=${WTTR_CACHE_TTL:-300}
+# Cache location.
+: "${WTTR_CACHE:="${HOME}/.cache/wttr/cached"}"
+# Cache ttl in seconds.
+: "${WTTR_CACHE_TTL:=300}"
+# Format string for the wttr API. See the Github page for more info about the
+# directives: https://github.com/chubin/wttr.in#one-line-output
+: "${WTTR_FMT:="%c+%t+(%f)+%p"}"
+# URL to the wttr API.
+: "${WTTR_URL:="http://wttr.in/?format=${WTTR_FMT}"}"
+
+# Print line to stderr.
+stderr() { echo "$@" >&2; }
 
 # Emit a debug line to stderr, if WTTR_DEBUG is set.
-debug() {
-    # set the WTTR_DEBUG env var to print debug logs
-    [ "${WTTR_DEBUG}" ] && echo "$@" >&2
-}
+# Run with `WTTR_DEBUG=1` to print debug logs.
+debug() { ( [ -n "${WTTR_DEBUG}" ] && stderr "$@" ) || true; }
+
+# Fetch the current timestamp, in unix seconds.
+now() { date +%s; }
 
 # Runs setup.
 setup() {
     # curl required, check that it's installed.
     if ! command -v curl > /dev/null; then
-        echo "error: missing curl"
+        stderr "error: missing curl"
         return 1
     fi
 
     # Create cache dir if not present.
-    cache_dir=$(dirname "${CACHE_FILE}")
+    cache_dir=$(dirname "${WTTR_CACHE}")
     if [ ! -d "${cache_dir}" ]; then
-        debug "creating dir for cache"
+        debug "creating missing cache dir dir=${cache_dir}"
         mkdir -p "${cache_dir}"
     fi
+    debug "setup: cache-file=${WTTR_CACHE} cache-ttl=${WTTR_CACHE_TTL}"
 }
 
+
 # Reads value from cache from stdin. Prints the result to stdout if its a cache hit.
-read_weather() {
-    read -r FETCHED_AT
-    NOW=$(date +%s)
-    DIFF=$((NOW - FETCHED_AT))
-    if [ ${DIFF} -lt "${CACHE_TTL}" ]; then
-        debug "cache hit: fetched at=${FETCHED_AT}, now=${NOW}, diff=${DIFF}"
-        read -r CACHED_RESULT
-        echo "${CACHED_RESULT}"
-    fi
+read_cache() {
+    # Two-lined input, first line being the time the result was fetched at and
+    # the second the actual output.
+    read -r fetched_at
+    read -r result
+
+    # Compare the cached fetch time to now and see if it's still valid.
+    ts_now=$(now)
+    diff=$((ts_now - fetched_at))
+    hit=$((diff < WTTR_CACHE_TTL))
+    debug "cache: hit=${hit} fetched-at=${fetched_at} now=${ts_now} diff=${diff}"
+
+    # Exit non-zero if this was not a cache hit, else print the result to stdout.
+    [ "${hit}" -eq 0 ] && return 255
+    echo "${result}"
 }
 
 # Writes the value $1 in the cache format to stdout.
-write_weather() {
-    NOW=$(date +%s)
-    printf "%s\n%s\n" "${NOW}" "${1}"
+write_cache() {
+    read -r weather
+    printf "%s\n%s\n" "$(now)" "${weather}"
+}
+
+# Run HTTP request to wttr.
+fetch_wttr() {
+    debug "fetch: url=${WTTR_URL}"
+    curl "${WTTR_URL}" 2>/dev/null
 }
 
 main() {
     # Run setup.
-    if ! setup; then exit 1; fi
-
-    debug "cache: file=${CACHE_FILE}, ttl=${CACHE_TTL}"
-
+    setup || exit 1
     # Check first if cached value is still live.
-    if [ -f "${CACHE_FILE}" ]; then
-        CACHED=$(read_weather < "${CACHE_FILE}")
-        if [ "${CACHED}" ]; then
-            echo "${CACHED}"
-            exit 0
-        fi
-    fi
-
+    [ -f "${WTTR_CACHE}" ] && read_cache < "${WTTR_CACHE}" && exit 0
     # Else, fetch from wttr.in.
-    debug "cache miss, fetching from wttr.in"
-    WEATHER=$(curl wttr.in/?format="%c+%t+(%f)+%p\n" 2>/dev/null)
-
+    weather="$(fetch_wttr)"
     # Write result to cache.
-    write_weather "${WEATHER}" > "${CACHE_FILE}"
-
+    echo "${weather}" | write_cache > "${WTTR_CACHE}"
     # Echo result to stdout.
-    echo "${WEATHER}"
+    echo "${weather}"
 }
 
 main < /dev/null
